MonitoringWeb/Controllers/MeteringDataController.cs
using MonitoringDB.Model.Sql;
using MonitoringDB.Model.Sql.Extentions;
using MonitoringWeb.Models;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MonitoringWeb.Controllers
{
    public class MeteringDataController : Controller
    {
        public async Task<ActionResult> Registration(long? pointId)
        {
            var model = new MeteringDataRegistrationModel();
            if (pointId.HasValue)
            {
                var meteringPoint = await MonitoringDbRepository.GetMeteringPointAsync(pointId.Value);
                model.PointId = pointId;
                model.MeteringPointOwner = meteringPoint.Owner;
                model.MeteringPointStreet = meteringPoint.Street;
                model.MeteringPointHouse = meteringPoint.House;
                model.MeteringPointFlat = meteringPoint.Flat;
            }
            return View("MeteringDataRegistration", model);
        }

        [HttpPost]
        public async Task<ActionResult> Registration(MeteringDataRegistrationModel model)
        {
            if (ModelState.IsValid)
            {
                MeteringPoint meteringPoint = null;
                if (!model.PointId.HasValue) 
                {
                    meteringPoint = new MeteringPoint
                    {
                        Owner = model.MeteringPointOwner,
                        Street = model.MeteringPointStreet,
                        House = model.MeteringPointHouse,
                        Flat = model.MeteringPointFlat
                    }; 
                }

                if (model.MeteringDataValue.HasValue)
                {
                    var meteringData = new MeteringData
                    {
                        PointId = model.PointId.GetValueOrDefault(),
                        MeteringPoint = meteringPoint,
                        CheckedAt = model.MeteringDataCheckedAt ?? DateTime.Now,
                        Value = model.MeteringDataValue.Value
                    };

                    await MonitoringDbRepository.SaveAsync(meteringPoint, meteringData, null, null);
                    ViewBag.ResultMessage = "Показания счетчика успешно зарегистрированы";
                    return View("MeteringDataRegistration");
                }
            }
            return View("MeteringDataRegistration", model);
        }
    }
}

MonitoringWeb/Controllers/MeteringDevicesController.cs
using MonitoringDB.Model.Sql;
using MonitoringDB.Model.Sql.Extentions;
using MonitoringWeb.Models;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MonitoringWeb.Controllers
{
    public class MeteringDevicesController : Controller
    {
        public async Task<ActionResult> Index(string house, int days = 5)
        {
            var meteringDevices = await MonitoringDbRepository.GetMeteringDevicesForCheckAsync(days, house);
            var devicesModel = meteringDevices
                .Select(mp => new MeteringDeviceModel {
                                                        DeviceType = mp.DeviceType,
                                                        SerialNo = mp.SerialNo,
                                                        CheckDate = mp.CheckDate
                                                    }).ToList();

            var model = new MeteringDevicesModel { DevicesForCheckFilter = new MeteringDevicesForCheckFilterModel { Days = days, House = house }, MeteringDevices = devicesModel };
            return View("Index", model);
        }

        public async Task<ActionResult> DevicesHistory(long pointId)
        {
            var meteringPoint = await MonitoringDbRepository.GetMeteringPointAsync(pointId);
            var model = new MeteringDevicesHistoryModel { 
                MeteringPoint = $"Адрес: улица {meteringPoint.Street} дом {meteringPoint.House} кв.{meteringPoint.Flat}; Владелец:{meteringPoint.Owner}",
                MeteringDevicesHistory = meteringPoint.MeteringDeviceHistory?.Select(h => new MeteringDevicesInfoModel {
                                                                                                                DeviceType = h.MeteringDevice.DeviceType,
                                                                                                                SerialNo = h.MeteringDevice.SerialNo,
                                                                                                                CheckDate = h.MeteringDevice.CheckDate,
                                                                                                                MountedAt = h.MountedAt,
                                                                                                                DemountedAt = h.DemountedAt
                                                                                                            })
                                                                                                                .OrderBy(h => h.MountedAt)
                                                                                                                .ToList()
            };
            return View("MeteringDevicesHistory", model);
        }

        public ActionResult Mount()
        {
            return View("MeteringDeviceMounting", new MeteringDeviceMountingModel());
        }

        [HttpPost]
        public async Task<ActionResult> Mount(MeteringDeviceMountingModel model)
        {
            if (ModelState.IsValid)
            {
                MeteringData meteringData = null;

                var meteringPoint = new MeteringPoint {
                    Owner = model.MeteringPointOwner,
                    Street = model.MeteringPointStreet,
                    House = model.MeteringPointHouse,
                    Flat = model.MeteringPointFlat
                };

                if (model.MeteringDataValue.HasValue)
                {
                    meteringData = new MeteringData {
                        MeteringPoint = meteringPoint,
                        CheckedAt = model.MeteringDataCheckedAt ?? DateTime.Now,
                        Value = model.MeteringDataValue.Value
                    };
                }

                var meteringDevice = new MeteringDevice { 
                    DeviceType = model.DeviceType, 
                    SerialNo = model.DeviceSerialNo, 
                    CheckDate = model.DeviceCheckDate 
                };

                var meteringDeviceInfo = new MeteringDeviceInfo
                {
                    MountedAt = model.MountedAt ?? DateTime.Now,
                    DemountedAt = model.DemountedAt,
                    MeteringDevice = meteringDevice,
                    MeteringPoint = meteringPoint
                };


                await MonitoringDbRepository.SaveAsync(meteringPoint, meteringData, meteringDevice, meteringDeviceInfo);

                ViewBag.ResultMessage = "Данные о счетчике успешно сохранены";
                return View("MeteringDeviceMounting");
            }
            return View("MeteringDeviceMounting", model);
        }
    }
}

MonitoringWeb/Controllers/MeteringPointsController.cs
using MonitoringDB.Model.Sql;
using MonitoringDB.Model.Sql.Extentions;
using MonitoringWeb.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MonitoringWeb.Controllers
{
    public class MeteringPointsController : Controller
    {
        const int rowsPerPage = 5;

        public async Task<ActionResult> Index(int page=0)
        {
            var query = MonitoringDbRepository.MeteringPointsInfoQuery();

            var count = query.Count();
            var pages = count / rowsPerPage;
            if (count % rowsPerPage > 0)
                pages++;

            ViewBag.Pages = pages;
            ViewBag.CurrentPage = page;

            int skip = 0;
            if (page > 0) skip = rowsPerPage * page;
            var take = rowsPerPage;

            var meteringPointsInfo = await MonitoringDbRepository.GetMeteringPointsInfoAsync(skip, take);
            var model = meteringPointsInfo.Select(mp => new MeteringPointModel
            {
                PointId = mp.Item1.PointId,
                Owner = mp.Item1.MeteringPoint.Owner,
                Street = mp.Item1.MeteringPoint.Street,
                House = mp.Item1.MeteringPoint.House,
                Flat = mp.Item1.MeteringPoint.Flat,
                DeviceValue = mp.Item1.Value,
                DeviceType = mp.Item2?.DeviceType,
                DeviceSerialNo = mp.Item2?.SerialNo,
                DeviceCheckDate = mp.Item2?.CheckDate
            }).ToList();

            return View("Index", model);
        }
    }
}

MonitoringWeb/Views/MeteringPoints/Index.cshtml
@model IList<MonitoringWeb.Models.MeteringPointModel>

@{
    ViewBag.Title = "Точки учета";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>Точки учета</h2>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h2 class="panel-title">Точки учета</h2>
            </div>
            <div class="panel-body">
                @Html.Partial("_MeteringPointsList", @Model)
            </div>
        </div>
    </div>

</div>

MonitoringWeb/Views/MeteringPoints/_MeteringPointsList.cshtml
@model IList<MonitoringWeb.Models.MeteringPointModel>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Владелец</th>
            <th>Адрес</th>
            <th>Тип счетчика</th>
            <th>Номер счетчика</th>
            <th>Показания</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Owner</td>
                    <td>@item.Address</td>
                    <td>@item.DeviceType</td>
                    <td>@item.DeviceSerialNo</td>
                    <td>@item.DeviceValue</td>
                    <td>
                        @Html.ActionLink("История замен счетчиков", "DevicesHistory", "MeteringDevices", new { pointId = item.PointId }, new { @class = "btn btn-primary btn-xs", @style = "color:white" })
                        @Html.ActionLink("Регистрация показаний", "Registration", "MeteringData", new { pointId = item.PointId }, new { @class = "btn btn-primary btn-xs", @style = "color:white" })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

@if (ViewBag.Pages != null && ViewBag.Pages > 0)
{
    <nav aria-label="">
        <ul class="pagination">
            @for (var page = 0; page < ViewBag.Pages; page++)
            {
                <li class="page-item"><a class="page-link" href="@Url.Action("Index", "MeteringPoints", new { page=page })">
                    @if (ViewBag.CurrentPage != null && ViewBag.CurrentPage == page)
                    {
                        <span style="font-weight: bold;">@(page + 1)</span>
                    }
                    else
                    {
                        @(page + 1)
                    }
                </a></li>
            }
        </ul>
    </nav>
}